### ISSUE TITLE
Invalid reference to DataTypeConverter.parse() method

### ISSUE THREAD

**Issue by Tomas-Kraus** [jakartaee/jaxb-api#242]
Section 7.9.2.1, "Usage" in the "DataTypeConverter" section, example titled
"javaType Customization: User Specified Parse Method". This references
"DatatypeConverter.parse(s)", which doesn't exist. In this context, it should
probably be "DataTypeConverter.parseDateTime(s)" instead.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.2]

**Comment by antoniosanct** [comment]
https://jakarta.ee/specifications/xml-binding/4.0/jakarta-xml-binding-spec-4.0#usage-6
