### ISSUE TITLE
Marshaller StAX API's underspecified

### ISSUE THREAD

**Issue by Tomas-Kraus** [jakartaee/jaxb-api#32]
The new StAX API's on javax.xml.bind.Marshaller are underspecified.

They need to explain when/if document level events are generated
on the XMLStreamWriter/XMLEventWriter.
#### Environment
Operating System: All
Platform: All
URL: [https://jsr222.dev.java.net/nonav/api/javax/xml/bind/Marshaller.html](https://jsr222.dev.java.net/nonav/api/javax/xml/bind/Marshaller.html)
#### Affected Versions
[2.0 v0.4]

**Comment by xerx593** [comment]
please close! "stax and jaxb" are like  "sausage and umbrella" (barely related things) ..or provide more details! :)
